### ISSUE TITLE
PhotosAccount.list_albums(): KeyError: 'albums'

### ISSUE THREAD

**Issue by nmd2117** [NicholasDawson/ArchiverForGooglePhotos#12]
![7f581a5b-3138-46bb-bc6e-ab968adef98d](https://user-images.githubusercontent.com/69922730/142047355-da854b4a-154e-452a-a2dc-2d87a1cbb67b.png)
This was submitted by a user and needs to be investigated as to why this could be happening.

Some possible fixes would be to add better debugging and add exceptions for this type of error to find the cause.

**Comment by NicholasDawson** [comment]
Fixed by @henryli17 with PR #13
