### ISSUE TITLE
Option to download only favorite photos from Google Photos

### ISSUE THREAD

**Issue by steveny2k** [NicholasDawson/ArchiverForGooglePhotos#2]
Photos in Google Photos are often too many to download all of them.
It would be great to provide an option to download only the favorite photos.

**Comment by NicholasDawson** [comment]
Favorite ones, as in the ones you have starred?

I can see if that's a parameter in the json that I download from.

Nick

**Comment by steveny2k** [comment]
Yes, I meant to say starred. Thanks!

**Comment by NicholasDawson** [comment]
I was reading up on this, and yes it is possible.

https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#Feature

I will take a look into this when I have some more time on my hands. I also have plans to multithreaded this application and make a CLI and maybe publish it as a python package.

I will keep you updated.

**Comment by steveny2k** [comment]
Great! many thanks!

**Comment by NicholasDawson** [comment]
I know this is a long time coming, but I recently updated the program and it can now download only favorites. Check it out!

**Comment by steveny2k** [comment]
Great! thanks.
Will try it out.

**Comment by steveny2k** [comment]
This new feature works quite well. Thanks!
