### ISSUE TITLE
Download loses exif data and considerable size

### ISSUE THREAD

**Issue by blacktav** [NicholasDawson/ArchiverForGooglePhotos#20]
Image files downloaded from a Shared album

1. file are severely compressed eg 2M instead of 8M
2. EXIFdata - specifically GPS data - has been removed

The same file downloaded through the web has all data intact

Why is this? Can it be easily avoided?

**Comment by blacktav** [comment]
Ah, it might be that the API is doing this - and Google of no intention of fixing that.

**Comment by NicholasDawson** [comment]
Yes, after research, this is a limitation of the API.
