### ISSUE TITLE
Duplicate Name Issue

### ISSUE THREAD

**Issue by safewithyou247** [NicholasDawson/ArchiverForGooglePhotos#21]
I have a ton of duplicate named photos in my Google Photos account and it looks like the app just skips them. Happy to help troubleshoot this if needed.

I have attached an example.

![Screenshot 2022-06-29 112855](https://user-images.githubusercontent.com/50427377/176488590-681642c4-4b64-4e62-baf7-1c39fa486610.png)
![Screenshot 2022-06-29 113016](https://user-images.githubusercontent.com/50427377/176488596-5d639c93-4c0e-4f48-a196-74a975383d39.png)

**Comment by NicholasDawson** [comment]
Interesting issue, after reading through the code I discovered a flaw in my auto file renaming logic. I can fix this hopefully in the next day or two and I will let you know here when it is done. Should be an easy fix.

Thank you for reporting!

**Comment by NicholasDawson** [comment]
@safewithyou247 The issue should be fixed now, sorry it took longer than expected. I am going to close this issue, but please report back on whether this issue has been fixed or not.

-Nick
