### ISSUE TITLE
Program closes before making folder

### ISSUE THREAD

**Issue by rw377** [NicholasDawson/ArchiverForGooglePhotos#5]
After following the google slides pages, everything goes through successfully. However, after seeing the confirmation page of the authentication flow working, the program closes and no folder is made.  The "photoslibrary_token.pickle" is in the directory, but nothing else is created.

**Comment by NicholasDawson** [comment]
Thanks for letting me know, I will be working on a fix in the next couple of days.

I will close this thread when it is fixed.

**Comment by NicholasDawson** [comment]
Should be fixed now, major changes were just made. Hope you find it helpful!
