### ISSUE TITLE
Exe stops right after starting

### ISSUE THREAD

**Issue by BalazsAdorjan** [NicholasDawson/ArchiverForGooglePhotos#6]
Followed the instructions, everything seemed fine, but the exe doesn't start downloading.
Managed to time this screenshot just right, before it quits.

![image](https://user-images.githubusercontent.com/18500095/127539343-9c2e5827-7f10-40e7-835c-a90b5774f996.png)
![image](https://user-images.githubusercontent.com/18500095/127539383-30b1bcbc-56a3-4249-8cae-666d0da596a1.png)

**Comment by Snuggle** [comment]
I'm also encountering this same issue on macOS. I've tried printing the request and oddly enough, `mediaItems` is within the `request` dictionary, so I'm not quite sure why this error is being generated.
```=============
SESSION STATS
=============
Seconds: 505.34s
Downloads: 0 items
Traceback (most recent call last):
  File "/Volumes/Homesweet/GooglePhotoArchiver/gparch_cli.py", line 127, in <module>
    account.download_library()
  File "/Volumes/Homesweet/GooglePhotoArchiver/gparch.py", line 281, in download_library
    items = self.process_media_items(self.list_media_items(), self.lib_dir)
  File "/Volumes/Homesweet/GooglePhotoArchiver/gparch.py", line 356, in list_media_items
    media_items_list += request["mediaItems"]
KeyError: 'mediaItems'```
