### ISSUE TITLE
Unable to Run to get all Albums or Photos

### ISSUE THREAD

**Issue by cobra88king8** [NicholasDawson/ArchiverForGooglePhotos#7]
Hello,

I have no problem downloading favorites or shared albums, however when I attempt to download albums or photos I encounter: **KerError: 'albums'** for Albums, or **gparch_cli: error: unrecognized arguments: Photos**. 

Otherwise this is a fantastic tool that does exactly what I've been looking for as Google Takeout is completely broken for me.

**Comment by NicholasDawson** [comment]
The KeyError: 'albums' issue should be fixed. And for the gparch_cli error, I think you may be using the command line arguments incorrectly, but let me know if this error persists. I'm going to close this issue for now.
