### ISSUE TITLE
RAW Images stored in Google Photos cannot be downloaded

### ISSUE THREAD

**Issue by Snuggle** [NicholasDawson/ArchiverForGooglePhotos#9]
It seems that raw photos from dedicated cameras that are stored in Google Photos won't be able to be downloaded as Python's pillow library doesn't seem to support them. As this is an upstream issue it might be difficult to find a fix, but it seems that most RAW formats aren't supported by Pillow and instead [rawpy](https://pypi.org/project/rawpy/) is usually used.

I have thousands of `.arw` images stored in my Google Photos which is a raw image format used by almost all Sony cameras.

**Upstream Issue:** https://github.com/python-pillow/Pillow/issues/3124

```python
✔ Finished Downloading Shared Albums.

Reading Entire Library From Server...

Downloading Library:  16%|████████████████████████████████████████████▉  | 3539/22777 [00:04<00:09, 1956.83 media items/s]
ERROR: media item could not be downloaded because: unknown file extension: .arw
ERROR: media item could not be downloaded because: unknown file extension: .arw
ERROR: media item could not be downloaded because: unknown file extension: .arw
ERROR: media item could not be downloaded because: unknown file extension: .arw
ERROR: media item could not be downloaded because: unknown file extension: .arw
```

**Comment by NicholasDawson** [comment]
The reason I use Pillow is to embed the description of a media item in Google Photos into the EXIF data of the downloaded image manually since this information is not stored in the image file, but in a database on their servers.

I don't think that RAW files would need this type of functionality and from my simple research, it seems EXIF data is not supported on RAW files.

I think I will add an exception that will just skip the Description field if the file is not supported by Pillow.

What do you think?

**Comment by Snuggle** [comment]
@NicholasDawson, hmm. I think .ARW files do still contain EXIF data. After popping one of my .ARWs from my Sony camera into this website http://exif.regex.info/exif.cgi I end up seeing the EXIF data below for example.

I would think that information such as lens type, ISO, exposure time, f/stop would be quite important to someone who took photos on a dedicated camera, so I'd keep all of this EXIF data if possible, though I can't see the use case for a 'Description' field.

Is skipping description but keeping all the other EXIF data an option?

![image](https://user-images.githubusercontent.com/26250962/131223958-c725fd01-c1fc-43ee-953d-4f4039816e16.png)

**Comment by NicholasDawson** [comment]
Yes by default the normal data included in the image is kept, the description field is appended to the existing exif data on the image.
